{{- if .Values.serviceMonitor.enabled -}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "hello-page-and-return-name.fullname" . }}
  labels:
  {{- include "hello-page-and-return-name.labels" . | nindent 4 }}
  {{- with .Values.serviceMonitor.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
  {{- include "hello-page-and-return-name.labels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  {{- with .Values.serviceMonitor.endpoints }}
  endpoints:
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
