apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-page-and-return-name.fullname" . }}
  labels:
    {{- include "hello-page-and-return-name.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hello-page-and-return-name.selectorLabels" . | nindent 4 }}
